name: Deploy PHP API

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    environment: prod

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Generate .env
        run: |
          echo "ACCOUNT_ID=${{ vars.R2_ACCOUNT_ID }}" >> .env
          echo "ACCESS_KEY=${{ vars.R2_ACCESS_KEY }}" >> .env
          echo "SECRET_KEY=${{ vars.R2_SECRET_KEY }}" >> .env
          echo "BUCKET_NAME=${{ vars.R2_BUCKET_NAME }}" >> .env

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}

          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
